spring:
  application:
    name: LMS.Discovery

server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      spring:
      main:
      web-application-type: none
      registerWithEureka: true
      fetchRegistry: true